Aardwolf-Social/aardwolf-social

- CODE_OF_CONDUCT.md
Requesting the Code of Conduct from @jennifermf
> Code of Conduct - Courtesy of Ghost

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- INSTALL.md
- README.md
Signed-off-by: Marcin Mikołajczak <me@m4sk.in>
> in fact, Mastodon has over 1000 instances

- src/bin/setup.rs
> Check the exit code of each subprocess instead of assuming success

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
I tried to incorporate everyone's suggestions into CONTRIBUTING.md, and tidied up some bad (or broken) formatting in the CoC.
> New CONTRIBUTING.md, edited CODE_OF_CONDUCT.md

- src/aardwolf/routes/app.rs
- src/bin/main.rs
- templates/sign_in.html.hbs
Add a route to /assets that serves assets
> Serve assets

- src/bin/main.rs
Sorry I broke your database pool stuff
> Add question mark to unwrap pool

- src/aardwolf/controllers/auth.rs
> Added logging for user create failed

- CONTRIBUTING.md
Remove "I" and add links on links on links
> UPDATE: Contributing

- aardwolf-models/migrations/2018-04-14-012342_add_direct_posts/down.sql
- aardwolf-models/migrations/2018-04-14-012342_add_direct_posts/up.sql
- aardwolf-models/migrations/2018-04-14-012357_add_groups/down.sql
- aardwolf-models/migrations/2018-04-14-012357_add_groups/up.sql
- aardwolf-models/migrations/2018-04-14-012407_add_group_base_actors/down.sql
- aardwolf-models/migrations/2018-04-14-012407_add_group_base_actors/up.sql
- aardwolf-models/src/base_actor/group/group_base_actor.rs
- aardwolf-models/src/base_actor/group/mod.rs
- aardwolf-models/src/base_actor/mod.rs
- aardwolf-models/src/base_actor/persona.rs
- aardwolf-models/src/base_post/direct_post.rs
- aardwolf-models/src/base_post/mod.rs
- aardwolf-models/src/lib.rs
- aardwolf-models/src/schema.rs
- aardwolf-models/src/user/permissions.rs
I accidentally overwrote my earlier changes creating Group and DirectPost types, so here they are again.
I also introduced a PersonaCreator that allows users with sufficient permissions to create personas.
> Add Persona creator, create Group and Direct Post types

- README.md
Quick touch-up to nomenclature, inaccuracies like this could be a turnoff to having other developers interested in contributing.
🥂
> readme fix: PostGRE is not a database

- CONTRIBUTING.md
one word was missing I think...I suggested one to put in...
> fixed small grammar issue in contributing.md

- aardwolf-server/src/aardwolf/routes/auth.rs
- aardwolf-server/templates/sign_up.html.hbs
fixes https://github.com/BanjoFox/aardwolf/issues/127
also formatting
> Fix sign-up 404

- package.json
- templates/home.html.hbs
- templates/htmlHead.html.hbs
- webpack.config.js
Simple webpack configuration that compiles JS, CSS and other assets files.
> Add barebone simple webpack configuration

- doc/README.md
- doc/TEMPLATE_LAYOUT.md
Remove tera templates, and Update documentation
> Remove tera templates

- config/example.toml
Re-organizing so that the most common changes (Instance name, server info, DB) are at the top.
> Updating example.toml

- package-lock.json
bug introduced in 
https://github.com/Aardwolf-Social/aardwolf/commit/405722e032f614aa9c39bbf4ea8ee1394027da82
> fix missing comma in package-lock.json

- Cargo.lock
- aardwolf-templates/Cargo.toml
- aardwolf-templates/src/containers/mod.rs
Exactly as the title says.  I opted to go with the re-export style I implemented elsewhere in the module for consistency.
> Fix container template module export

- aardwolf-models/src/sql_types/timezone.rs
Applied suggested fixes, and ran `cargo clippy` to verify.
Should be all good.
> Minor update to remove explicit lifetime.

- Cargo.lock
- Cargo.toml
- aardwolf-actix/Cargo.toml
- aardwolf-localization/Cargo.toml
- aardwolf-models/Cargo.toml
- aardwolf-templates/Cargo.toml
- aardwolf-types/Cargo.toml
- aardwolf-yew-frontend/Cargo.toml
> Bump versions across multiple Cargo manifests

- Cargo.lock
Testing that 'cargo update` works.
> Run 'cargo update' and push updated 'Cargo.lock' file.

- .github/workflows/aardwolf-build.yml
- .github/workflows/docker.yml
- .github/workflows/rust-clippy.yml
Hopefully this identifies why not all CI actions are running.
> Updating workflow syntax.  
