Aardwolf-Social/aardwolf-social

Cargo.toml

Just fixing a mistake in Cargo.toml

Cargo prefers "snake-case" package names

---

.travis.yml

Rocket.rs does not currently compile on stable or beta, so our build
will fail until that is no longer the case.

Remove `stable` and `beta` from travis config

---

INSTALL.md

This tripped me up when I tried running it as I thought I'd already dealt with the DB config in the `DATABASE_URL` env var. Add a note that you have to set the key in the `Rocket.toml` too so other don't get tripped up.

Add details of Rocket database_url to install instructions

---

src/aardwolf/controllers/auth.rs
src/aardwolf/models/account.rs
src/aardwolf/models/user.rs
src/aardwolf/routes/app.rs
src/aardwolf/routes/auth.rs

Gets us almost warning-free. The only ones left will either be taken
care of in an upcoming PR, or come from derive_builder and will be fixed
as soon as a new version of that crate is released

Fix a bunch of warnings

---

Cargo.lock
Cargo.toml
src/bin/common.rs
src/bin/main.rs
src/bin/setup.rs
src/bin/setup.yml

This should eliminate the need to set `DATABASE_URL` or use the `diesel` command when a developer is getting up-and-running
Instead of having to run
```
$ DATABASE_URL=foobar diesel setup
$ DATABASE_URL=foobar diesel migration run
```
with this you just run
```
$ cargo run --bin setup
```
and it should take care of the db for you.

Add setup command

---

INSTALL.md

So, this is just a little note added to the INSTALL.md that tells Fedora/CentOS/RHEL users which postgresql packages they need, because in my experience, people won't install postgresql-contrib unless they're specifically told they need to.

Add Fedora install instructions for postgresql

---

README.md

Not sure if what I did to the link for the license in line 83 is right. There was a square bracket after the link for the svg file, and it was looking strange on output on the readme file here on github. I took out that square bracket but I'm not sure if that was the right thing to do.

fixed some typos and links on readme

---

Cargo.toml
aardwolf-models/Cargo.toml
aardwolf-models/src/lib.rs
aardwolf-models/src/sql_types/follow_policy.rs
aardwolf-models/src/sql_types/post_visibility.rs
aardwolf-models/src/sql_types/url.rs
aardwolf-models/src/user/email/token.rs
aardwolf-models/src/user/local_auth/password.rs

This change puts rocket behind a feature flag for aardwolf-models
useful for https://github.com/Aardwolf-Social/aardwolf/issues/151

Remove models' dependency on Rocket

---

aardwolf-models/migrations/2019-01-18-211319_make_private_key_nullable/down.sql
aardwolf-models/migrations/2019-01-18-211319_make_private_key_nullable/up.sql
aardwolf-models/src/base_actor/mod.rs
aardwolf-models/src/schema.rs
aardwolf-models/src/test_helper.rs

Private Keys will only be stored for local actors, so they shouldn't be mandatory

Make private key optional

---

Cargo.lock
aardwolf-actix/Cargo.toml
aardwolf-actix/src/lib.rs
aardwolf-actix/src/routes/personas.rs
aardwolf-models/migrations/2019-01-18-212737_add_activitypub_ids/down.sql
aardwolf-models/migrations/2019-01-18-212737_add_activitypub_ids/up.sql
aardwolf-models/src/base_actor/mod.rs
aardwolf-models/src/base_post/mod.rs
aardwolf-models/src/schema.rs
aardwolf-models/src/test_helper.rs
aardwolf-models/src/user/permissions.rs
aardwolf-rocket/Cargo.toml
aardwolf-rocket/src/lib.rs
aardwolf-rocket/src/routes/personas.rs
aardwolf-types/src/operations/create_persona.rs

It doesn't make sense to have ActivityPub Objects without IDs.
This also introduces the GenerateUrls trait, which can be used to create URLs from a UUID without the models needing to know what the URL scheme is

Add ActivityPub IDs to Posts and Actors

---

doc/SETUP-NGINX.md
doc/SETUP-POSTGRES.md
doc/SETUP-WEBPACK.md
webpack.config.js

To make the documentation more consistent, I reformatted everything to follow how `INSTALL-RUST.md` was formatted.
I also tweaked the webpack install guide to use the existing [`package.json`](https://github.com/Aardwolf-Social/aardwolf/blob/master/package.json) rather then creating a new one.

Update documentation formatting

---

.travis.yml

Just what the commit says.
Bump Travis postgresql from 9.6 to 13.2

Update travis postgresql version to 13.2

---

.github/workflows/docker.yml
.github/workflows/label.yml
.github/workflows/rust.yml

Adding the following workflows from the stock GitHub Actions menu:
- Rust builder
- Docker builder
- Labeler (for labeling PR's)

Add GitHub actions for Rust, Docker, and Labels

---

src/bin/cli.toml
src/bin/setup.toml

Created TOML-formatted versions of the two YAML-formatted files in /src/bin.
The reasoning for this is the fact that `yaml-rust` crate hasn't been updated in 4 years, and Clap hasn't supported YAML parsing since version 3.0.0 (current is 4.3.8).
TOML seems to be more widely supported, and in fact is required by Rust for the `rust-toolchain` file.

Create TOML versions of CLI and SETUP YAMLs

---

Cargo.lock
Cargo.toml
aardwolf-actix/Cargo.toml
aardwolf-templates/Cargo.toml

Re-adds the following changes that I accidentally stripped from a previous PR.
* remove the actix flag from rocket_i18n (`cargo build` crashes on stable if it is on)
* Removes the minor version from the clap dependency declaration

Remove actix feature from rocket_i18n dependency declaration so "cargo build" succeeds

---

aardwolf-actix/src/routes/auth.rs

Fixes remaining deprecated used of `header`

Fix actix/routes/auth header -> append_header

---

Cargo.toml
src/lib.rs
src/new-broken-lib.rs

This PR splits the /src/lib.rs into two versions.  The original; which uses deprecated code (replace with config::Builder), and the most recent shot at creating the config::Builder variant (which is broken: `config run --bin setup`)

Banjofox/fix src lib.rs

---

.github/workflows/aardwolf-build.yml
.github/workflows/aardwolf-test.yml
.github/workflows/docker.yml

- Update `aardwolf-build.yml` to use more verbose names
- Update `aardwolf-test.yml` to fix syntax of the `workflow_run` to require `CI Build` to be completed before running tests.
- Update `docker.yml` to fix branch name for 'main', and bump actions/checkout to v4

Improve Github Actions

---

README.md

Updating instances of "Aardwolf" with "Aardwolf Social" in order to fully distinguish our project with the MUD

Update README.md - /s/Aardwolf/Aardwolf Social

---

.github/workflows/docker.yml
aardwolf-yew-frontend/Cargo.toml
docker/Dockerfile

**Description**: This PR addresses a issues that were preventing the Docker image from building successfully.
**before**: The build command was not specifying the correct context folder where the Dockerfile and related scripts are located giving error. `ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory`
**after**: Updated the Docker build command to set the context correctly to the docker directory.
After addressing the above issues, a new error has arisen related to the entry point script. During the build process, Docker throws an error indicating that docker-entrypoint.sh cannot be found.
`ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref f45fc31b-ef18-4a5f-be2b-7f841a08fbe4::1voajrdg166rvuhs16k60a5b1: …

[Fix Docker Builds #334] changed the dockerfile path in docker.yaml workflow
